export default {
  welcome: "Hi! My name's",
  welcome_2: 'EasyFlat24',
  welcome_3: 'I can In Hac',
  welcome_4: 'Habitasse Platea',
  welcome_5: 'Pellentesque ullamcorper metus in est',
  welcome_6: 'fermentum gravida.',
  welcome_7: "Oh, you're new.",
  welcome_8: "I'd like to know more about you.",
  skip: 'Skip',
  next: 'Next',
  your_basic_information: 'YOUR BASIC INFORMATION',
  firstname: 'Firstname',
  lastname: 'Lastname',
  telephone: 'Telephone',
  keep_your_information_safe: 'KEEP YOUR INFORMATION SAFE',
  password: 'Password',
  re_enter_password: 'Re-enter password',
  confirm: "I've read and agree to the",
  and: 'and',
  term: 'Terms',
  data_use_policy: 'Data Use Policy.',
  create_an_account: 'Create An Account',
  enter_pin_code: 'Enter Pincode',
  enter_your_pin: 'Enter your PIN',
  welcome_back: 'Welcome back,',
  where_do_you_live: 'Where do you live?',
  post_code: 'Postcode',
  street: 'Street',
  house_number: 'House Number',
  find_offers: 'Find Offers',
  sorry: "I'm sorry!",
  sorry_explaination_1: 'Your address is not supported',
  sorry_explaination_2: 'at this time. I will send you a',
  sorry_explaination_3: 'message once I do.',
  how_many_people_live_in: 'HOW MANY PEOPLE LIVE IN',
  your_house_hold: 'YOUR HOUSE HOLD',
  package: 'Package',
  electricity: 'ELECTRICITY',
  data: 'DATA',
  bandwidth: 'BANDWIDTH',
  total: 'TOTAL',
  add_payment_method: 'ADD_PAYMENT_METHOD',
  choose_extra_services: 'CHOOSE EXTRA SERVICES',
  do_you_have_a_promotion_code: 'DO YOU HAVE A PROMOTION CODE?',
  your_code: 'Your code',
  total_monthly_price: 'TOTAL MONTHLY PRICE',
  payment_method: 'PAYMENT METHODS',
  credit_card: 'Credit Card',
  paypal: 'Paypal',
  make_contract: 'MAKE CONTRACT',
  contract_is_made: 'CONTRACT IS MADE',
  card_number: 'Card Number',
  card_holder_name: 'Cardholder Name',
  expired_date: 'Expired date',
  cvv: 'CVV',
  account: 'Account',
  payment_info: 'Payment Info',
  security_and_alert: 'Security & Alert',
  faq: 'FAQ',
  feedback: 'Feedback',
  contact_us: 'Contact Us',
  current_services: 'Current Services',
  nofitications: 'Notifications',
  touch_id: 'Touch ID',
  change_quick_code: 'Change quick code',
  manage_devices: 'Manage devices',
  alert: 'Receive via email',
  push_to_mobile: 'Push to Mobile',
  search: 'Search',
  select_a_category: 'Select a Category',
  message: 'Message',
  contact_support: 'Contact Support',
  plan_detail: 'Plan details',
  basic: 'Basic',
  price: 'Price',
  change_plan: 'Change Plan',
};
