const images = {
  account: require('./account.png'),
  arrow_right: require('./arrow_right.png'),
  back: require('./back.png'),
  calendar: require('./calendar.png'),
  complete: require('./complete.png'),
  contact_us: require('./contact_us.png'),
  edit: require('./edit.png'),
  face_id: require('./face_id.png'),
  face_id_error: require('./face_id_error.png'),
  face_id_success: require('./face_id_success.png'),
  faq: require('./faq.png'),
  feedback: require('./feedback.png'),
  finger_print: require('./finger_print.png'),
  finger_print_checking: require('./finger_print_checking.png'),
  global: require('./global.png'),
  hamburger_left: require('./hamburger_left.png'),
  hamburger_right: require('./hamburger_right.png'),
  lightning: require('./lightning.png'),
  mail: require('./mail.png'),
  netflix: require('./netflix.png'),
  netflix_medium: require('./netflix_medium.png'),
  netflix_red: require('./netflix_red.png'),
  netflix_red_big: require('./netflix_red_big.png'),
  onboarding: require('./onboarding.png'),
  onboarding_new: require('./onboarding_new.png'),
  onboarding_sorry: require('./onboarding_sorry.png'),
  payment: require('./payment.png'),
  paypal: require('./paypal.png'),
  pincode: require('./pincode.png'),
  prime: require('./prime.png'),
  prime_blue: require('./prime_blue.png'),
  search: require('./search.png'),
  security: require('./security.png'),
  send: require('./send.png'),
  simple_visa: require('./simple_visa.png'),
  tel: require('./tel.png'),
  visa: require('./visa.png'),
  welcome_back: require('./welcome_back.png'),
};

export default images;
