const images = {
  account: require('./resources/account.png'),
  arrow_right: require('./resources/arrow_right.png'),
  back: require('./resources/back.png'),
  calendar: require('./resources/calendar.png'),
  complete: require('./resources/complete.png'),
  contact_us: require('./resources/contact_us.png'),
  edit: require('./resources/edit.png'),
  face_id: require('./resources/face_id.png'),
  face_id_error: require('./resources/face_id_error.png'),
  face_id_success: require('./resources/face_id_success.png'),
  faq: require('./resources/faq.png'),
  feedback: require('./resources/feedback.png'),
  finger_print: require('./resources/finger_print.png'),
  finger_print_checking: require('./resources/finger_print_checking.png'),
  global: require('./resources/global.png'),
  hamburger_left: require('./resources/hamburger_left.png'),
  hamburger_right: require('./resources/hamburger_right.png'),
  lightning: require('./resources/lightning.png'),
  mail: require('./resources/mail.png'),
  netflix: require('./resources/netflix.png'),
  netflix_medium: require('./resources/netflix_medium.png'),
  netflix_red: require('./resources/netflix_red.png'),
  netflix_red_big: require('./resources/netflix_red_big.png'),
  onboarding: require('./resources/onboarding.png'),
  onboarding_new: require('./resources/onboarding_new.png'),
  onboarding_sorry: require('./resources/onboarding_sorry.png'),
  payment: require('./resources/payment.png'),
  paypal: require('./resources/paypal.png'),
  pincode: require('./resources/pincode.png'),
  prime: require('./resources/prime.png'),
  prime_blue: require('./resources/prime_blue.png'),
  search: require('./resources/search.png'),
  security: require('./resources/security.png'),
  send: require('./resources/send.png'),
  simple_visa: require('./resources/simple_visa.png'),
  tel: require('./resources/tel.png'),
  visa: require('./resources/visa.png'),
  welcome_back: require('./resources/welcome_back.png'),
};

export default images;
